FROM docker.io/openjdk:11-jre-slim
ENV JAVA_HOME /usr/local/openjdk-11
ENV PATH $PATH:$JAVA_HOME/bin/
ENV WEATHER_DB_HOST=${WEATHER_DB_HOST}
ENV WEATHER_DB_PORT=${WEATHER_DB_PORT}
ENV WEATHER_DB_NAME=${WEATHER_DB_NAME}
ENV WEATHER_DB_USERNAME=${WEATHER_DB_USERNAME}
ENV WEATHER_DB_PASSWORD=${WEATHER_DB_USERNAME}
ENV WEATHER_API_ID=${WEATHER_API_ID}
EXPOSE 8085
ADD target/coding-dojo-spring-boot-0.0.1-SNAPSHOT.jar weather.jar
ENTRYPOINT ["java","-jar","/weather.jar"]