version: '3'
services:
  postgres:
    image: "postgres:13"
    container_name: "postgres"
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${WEATHER_DB_USERNAME}
      - POSTGRES_PASSWORD=${WEATHER_DB_PASSWORD}
      - POSTGRES_DB=${WEATHER_DB_NAME}
  weather:
    container_name: weather
    build:
      context: ""
      dockerfile: Dockerfile
    image: weather:latest
    depends_on:
      - postgres
    expose:
      - 8085
    ports:
      - 8085:8085
    environment:
      - WEATHER_DB_HOST=${WEATHER_DB_HOST}
      - WEATHER_DB_PORT=${WEATHER_DB_PORT}
      - WEATHER_DB_NAME=${WEATHER_DB_NAME}
      - WEATHER_DB_USERNAME=${WEATHER_DB_USERNAME}
      - WEATHER_DB_PASSWORD=${WEATHER_DB_PASSWORD}
      - WEATHER_API_ID=${WEATHER_API_ID}
